# Generated by Django 5.0.1 on 2024-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Sous direction vente', 'Sous direction vente'), ('Directeur général', 'Directeur général'), ('Livreur', 'Livreur')], max_length=50),
        ),
    ]
