# Generated by Django 5.0.1 on 2024-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_accountrequest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='password',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='password1',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
