# Generated by Django 5.0.1 on 2024-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_accountrequest_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='password1',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='password',
            field=models.CharField(default='temporary_password', max_length=48),
        ),
    ]
