# Generated by Django 5.0.1 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Non Livrée'), ('in_progress', 'En cours de livraison'), ('delivered', 'Livrée')], default='pending', max_length=20),
        ),
    ]
