# Generated by Django 5.0.1 on 2024-06-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_ordercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_state',
        ),
    ]
